### ISSUE TITLE
구글 드라이브 링크 깨짐

### ISSUE THREAD

**Issue by sohee-zoe** [husuninder/ORBSLAM3_study#1]
안녕하세요. 
좋은 자료를 공유해주셔서 감사합니다.
하지만 안타깝게도 현재 구글 공유 링크가 깨져있는데 새로 공유가 가능한지 알고 싶습니다.

좋은 하루 보내세요.
감사합니다.

**Comment by husuninder** [comment]
안녕하세요. 
링크가 깨져 있는지 몰랐네요! 
왠지 모르겠지만 자료가 사라졌네요. 찾아보고 알려드리도록 하겠습니다.

감사합니다.

**Comment by husuninder** [comment]
링크 수정했습니다~
